# Generated by Django 3.2.16 on 2023-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CompanyId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CompanyName', models.CharField(max_length=255)),
                ('CompanySymbol', models.CharField(max_length=255)),
                ('CompanyDescriptionLong', models.TextField()),
                ('CompanyDescriptionShort', models.TextField()),
                ('CompanyType', models.CharField(max_length=255)),
                ('AlchemyPage', models.URLField()),
                ('CareersPage', models.URLField()),
                ('HrProvider', models.CharField(max_length=255)),
                ('HrPage', models.CharField(max_length=255)),
                ('Website', models.URLField()),
                ('Image', models.URLField()),
                ('Twitter', models.URLField()),
                ('Tags', models.JSONField()),
                ('Chains', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('JobTitle', models.CharField(max_length=255)),
                ('JobLocation', models.CharField(max_length=255)),
                ('ApplyURL', models.URLField()),
                ('CompanyName', models.CharField(max_length=255)),
                ('CompanySymbol', models.CharField(max_length=255)),
            ],
        ),
    ]
