# Generated by Django 3.2.16 on 2023-09-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='jobs',
        ),
    ]
