# Generated by Django 3.2.16 on 2023-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0002_auto_20230920_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='AlchemyPage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CareersPage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Chains',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CompanyDescriptionLong',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CompanyDescriptionShort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CompanySymbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='CompanyType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='HrPage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='HrProvider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
