# Generated by Django 3.2.16 on 2023-09-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0003_auto_20230920_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='AlchemyPage',
            new_name='alchemy_page',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CareersPage',
            new_name='careers_page',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Chains',
            new_name='chains',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyId',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyName',
            new_name='company_type',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanySymbol',
            new_name='hr_page',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyType',
            new_name='hr_provider',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyDescriptionLong',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='HrPage',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyDescriptionShort',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='HrProvider',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Twitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='ApplyURL',
            new_name='apply_url',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='CompanySymbol',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='CompanyName',
            new_name='company_symbol',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='JobId',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='JobLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='JobTitle',
            new_name='title',
        ),
    ]
