# Generated by Django 3.2.16 on 2023-09-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0004_auto_20230920_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_type',
            new_name='service_type',
        ),
    ]
