# Generated by Django 3.2.21 on 2023-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0006_companies_hr_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
