# Generated by Django 3.2.21 on 2023-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dejobs_api', '0007_auto_20230922_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
