"""
Django settings for dejobsAPI project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path


class PROD_DEJOBS_DB_CREDENTIALS(object):
    HOST = 'oregon-postgres.render.com'
    NAME = 'dejobs_db'
    USER = "seif"
    PWD = "DU2ZJtBuGjg4dy5uaDDVkQLsFYHfG0HI"
    PORT = '5432'


class LOCAL_DEJOBS_DB_CREDENTIALS(object):
    HOST = 'localhost'
    NAME = 'dejobs_db'
    USER = "seif"
    PWD = "12345678"
    PORT = '5432'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w&(2-t8a(%@ywc6_lepv12qwem-y02u8rhm3j@(&a5^xa+d=21'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'dejobs_api.apps.DejobsApiConfig',
]

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dejobsAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dejobsAPI.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': LOCAL_DEJOBS_DB_CREDENTIALS.NAME,
    #     'USER': LOCAL_DEJOBS_DB_CREDENTIALS.USER,
    #     'PASSWORD': LOCAL_DEJOBS_DB_CREDENTIALS.PWD,
    #     'HOST': LOCAL_DEJOBS_DB_CREDENTIALS.HOST,
    #     'PORT': LOCAL_DEJOBS_DB_CREDENTIALS.PORT,
    # },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': PROD_DEJOBS_DB_CREDENTIALS.NAME,
        'USER': PROD_DEJOBS_DB_CREDENTIALS.USER,
        'PASSWORD': PROD_DEJOBS_DB_CREDENTIALS.PWD,
        'HOST': PROD_DEJOBS_DB_CREDENTIALS.HOST,
        'PORT': PROD_DEJOBS_DB_CREDENTIALS.PORT,
    },

}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
